---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 5
production:
  :concurrency: 10
:queues:
  - audit_commits
  - collect_commits
  - enqueue_projects
  - initial_audits
:limits:
  initial_audits: 1
  collect_commits: 3
