0:
  :name: 'not triaged'
  :description: 'Commit has not been triaged.'
1:
  :name: 'vulnerability'
  :description: 'Commit has been triaged and appears to be a vulnerability.'
2:
  :name: 'not vulnerability'
  :description: 'Commit has been triaged and does NOT appear to be a vulnerability.'
3:
  :name: 'unknown'
  :description: 'Commit has been triaged but its super confusing and should be looked at later.'
4:
  :name: 'not relevant'
  :description: 'Commit is not relevant for analysis, e.g. project is not a library.'
